from pathlib import Path

from app.models import WordRecord
from app.page_renderer import write_word_page


def test_write_word_page_includes_key_content(tmp_path: Path) -> None:
    word = WordRecord(
        id=1,
        word="Haus",
        article="das",
        translation="house",
        short_definition="A building",
        part_of_speech="noun",
        example_de="Das Haus ist alt.",
        example_translation="The house is old.",
        source="test",
        tags="home",
        difficulty=1,
        times_shown=0,
        last_shown_at=None,
        created_at="",
        updated_at="",
        is_active=1,
    )

    page_path = write_word_page(tmp_path, word)

    html = page_path.read_text(encoding="utf-8")
    assert page_path.name == "das-haus.html"
    assert "das Haus" in html
    assert "house" in html
    assert "Das Haus ist alt." in html
    assert "A building" not in html
    assert "The house is old." not in html
    assert 'id="pronounce-button"' in html
    assert 'id="pronounce-example-button"' in html
    assert "SpeechSynthesisUtterance" in html
    assert '"Haus"' in html
    assert '"Das Haus ist alt."' in html
    assert "Generated by German Word Notifier" in html
